### ISSUE TITLE
Some issues for axon explorer

### ISSUE THREAD

**Issue by liya2017** [Magickbase/blockscan#21]
1. explorer shows wrong date, today is June 10 , but explorer  shows June 1
<img width="1382" alt="image" src="https://user-images.githubusercontent.com/32123500/173010648-c363eead-8bf7-4757-9d2a-961d3d9faa44.png">

2. seems wrong Total blocks. current block hight shows  8184 on explore, actually axon total blocks is 498
<img width="1376" alt="image" src="https://user-images.githubusercontent.com/32123500/173010932-0d63fb92-8251-41ec-bbca-69322bf3980e.png">

3. The block number does not change . Axon block hight is 8819, but the explore still shows 8185, and the transactions also not up-to-date
<img width="687" alt="image" src="https://user-images.githubusercontent.com/32123500/173011380-5b3ba7bc-da39-4b99-b66d-6496f27c167a.png">
<img width="1271" alt="image" src="https://user-images.githubusercontent.com/32123500/173011421-04a6a998-3a55-4b0c-be63-125f03726c7c.png">

4. Explore will back to some lower block hight when container restart :
before container restart:
<img width="1307" alt="image" src="https://user-images.githubusercontent.com/32123500/173011833-bb00438d-b3d2-4818-8688-7144330b44ee.png">

after  container restart:
<img width="1050" alt="image" src="https://user-images.githubusercontent.com/32123500/173011906-dae9a7be-2894-44b2-b3b0-e6e555389042.png">

**Comment by mfuuzy** [comment]
hi, I have encountered the same problem. Do you have any progress on this problem?

**Comment by Naupio** [comment]
issue is in processing

**Comment by Naupio** [comment]
update with blockscout v5.1.1-beta version https://github.com/Magickbase/blockscan/commit/dd11a279c96a3d3da89573cd8f33c2e32ee56851
