### ISSUE TITLE
On the validated transactions page, click the block to display internal server error

### ISSUE THREAD

**Issue by Dawn-githup** [Magickbase/blockscan#27]
*On the validated transactions page, click the block to display internal server error.*

### Steps to reproduce
![image](https://user-images.githubusercontent.com/77844990/177488036-5203363f-e4b8-4dcd-b449-d22aa1299dfb.png)

### Expected behaviour

*Jump to the block page of the directory*

### Actual behaviour

*Internal server error.*

**Comment by Naupio** [comment]
seems cause error with `3.0` args for `Gettext.dpngettext(Timex.Gettext, "units", nil, "%{count} second", "%{count} seconds", 3.0, %{})`, the position of `3.0` must use `integer` type value.

**Comment by Naupio** [comment]
fixed here #29
