### ISSUE TITLE
Internal Server Error when trying to view any transaction logs

### ISSUE THREAD

**Issue by Kuzirashi** [Magickbase/blockscan#30]
Internal Server Error when trying to view any transaction logs.

Blockscan container logs:
```
blockscan  | Request: GET /tx/0x89d1f32693933c95952ab9f1dfb3e89c556528dc84f51c10187802565416f5f2/logs
blockscan  | ** (exit) an exception was raised:
blockscan  |     ** (Ecto.NoPrimaryKeyFieldError) schema `Explorer.Chain.Address.Name` has no primary key
blockscan  |         (ecto 3.8.4) lib/ecto/repo/assoc.ex:116: Ecto.Repo.Assoc.create_accs/4
blockscan  |         (elixir 1.13.1) lib/enum.ex:1593: Enum."-map/2-lists^map/1-0-"/2
blockscan  |         (ecto 3.8.4) lib/ecto/repo/assoc.ex:109: Ecto.Repo.Assoc.create_accs/4
blockscan  |         (elixir 1.13.1) lib/enum.ex:1593: Enum."-map/2-lists^map/1-0-"/2
blockscan  |         (ecto 3.8.4) lib/ecto/repo/assoc.ex:109: Ecto.Repo.Assoc.create_accs/4
blockscan  |         (ecto 3.8.4) lib/ecto/repo/assoc.ex:19: Ecto.Repo.Assoc.query/4
blockscan  |         (ecto 3.8.4) lib/ecto/repo/queryable.ex:226: Ecto.Repo.Queryable.execute/4
blockscan  |         (ecto 3.8.4) lib/ecto/repo/queryable.ex:19: Ecto.Repo.Queryable.all/3
```

Always `NoPrimaryKeyFieldError` is thrown in the internal logs.

![image](https://user-images.githubusercontent.com/4950658/210595005-9dd9032c-16d9-4ca0-9042-cc811819c1c9.png)

URL: https://khalani-axon-explorer-staging.digipnyx.org/tx/0x89d1f32693933c95952ab9f1dfb3e89c556528dc84f51c10187802565416f5f2/logs
RPC: https://www.axon-node.info

### Environment

* Operating System: Ubuntu 22.04.1 LTS
* Blockscout Version/branch: main

### Steps to reproduce

1. Go to any transaction in the Axon explorer, eg.: https://axon-explorer.digipnyx.org/tx/0x89d1f32693933c95952ab9f1dfb3e89c556528dc84f51c10187802565416f5f2
2. Click "Logs"
![image](https://user-images.githubusercontent.com/4950658/210595609-886c405e-ae60-4a12-89ec-c5c29f159418.png)

### Expected behaviour

Logs/events from the chain are displayed

### Actual behaviour

Internal Server Error

**Comment by Keith-CY** [comment]
Please have a look at this issue @Naupio

**Comment by Naupio** [comment]
issue is in processing

**Comment by Naupio** [comment]
update with blockscout v5.1.1-beta version https://github.com/Magickbase/blockscan/commit/dd11a279c96a3d3da89573cd8f33c2e32ee56851
